### ISSUE TITLE
/run/anbox-container.socket: No such file or directory

### ISSUE THREAD

**Issue by iamironz** [anbox/anbox-modules#29]
Hey. Faced this type of issue: 

```
[ 2019-08-16 15:04:25] [daemon.cpp:61@Run] Failed to connect to socket /run/anbox-container.socket: No such file or directory
```
What's this one indicates for?

**Comment by JasMich** [comment]
You need to start the `container-manager` service. Did you use the SNAP or the native package?

Try
```
sudo systemctl start anbox-container-manager.service
sudo systemctl enable anbox-container-manager.service 
```

**Comment by iamironz** [comment]
Yes, after this command this works fine. Thank you!

**Comment by miferg** [comment]
I compiled from source and have the same problem, when I run `systemctl start anbox-container-manager.service` I get `Failed to start anbox-container-manager.service: Unit anbox-container-manager.service not found.`
