### ISSUE TITLE
Snap can't find libudev.so.1 despite it being installed

### ISSUE THREAD

**Issue by DwarfFighterCleric** [anbox/anbox-modules#35]
I have libudev.so.1 installed, so why can't the snap find it? Is there a way to modify/unsquashfs the Snap package before it is installed? After it's installed it mounts as read-only, and in my particular version (xubuntu 16.04.3 very old) the particular snap "Core" can't even be removed or unmounted!

**Comment by morphis** [comment]
Without further details on the actual problem (What are you doing to get this error?) we're not able to help. Please describe the problem more in detail and how it can be reproduced.

**Comment by tlchatt** [comment]
Same problem super frustrating, /snap/core/10773/usr/lib/snapd/snap-confine: error while loading shared libraries: libudev.so.1: failed to map segment from shared object this erro when running any snap app.
