### ISSUE TITLE
Could you make anbox10 or similar branch?

### ISSUE THREAD

**Issue by sageyun1057** [anbox/anbox-modules#39]
I porting android 10 in Anbox.
So, I wish 'Pull requests' my code to your repositories.
In this time only display enabled, but I will support touch event and networks ASAP.
Can you make anbox10 or other similar branch to push my code to your branch? 
(anbox-moudeues and other repositories)

**Comment by JasMich** [comment]
Great idea! I once failed for Android 9 but if you need help, just tell me. What do you think @morphis ?
@sageyun1057 Did you already finish porting to Android 10 or di you want to start? If you didn't finish yet, you could just do it in a branch of your fork.

**Comment by sageyun1057** [comment]
@JasMich I already finish that start app via "anbox launch"  command.
I cleaning up my source code commit by commit now.
(Some git's uploaded in my account.)

In this time, I only enable dispaly. Touch and network not yet ported. But I thinkt that these are easier than hwcomposer.

**Comment by JasMich** [comment]
Great! Seems to be really good work. Could you share us your git repo's url? I guess before **morphis** will create a new branch some others of us should try and improve on.

Another important fact is documentation: As Android 10 won't be the last Android version, it would be great to see what (and how) you did.

**Comment by sageyun1057** [comment]
You can download via 
repo init -u https://github.com/sageyun1057/platform_manifests.git -b anbox10
(https://github.com/sageyun1057/platform_manifests)
(Originally, I didn't want upload manifast in my branch. 
In this case, in git history, my ID appears. When you make anbox10, consider about it.)

(I downloading now to test. I only worked in locally)

And I know that Android 10 is latest version. (Android Q)
In my knowlge Android Q MR1 is not released yet. 

The exactly version is "android-10.0.0_r2".
I also agree about documentation.
But as I say that it only enable display and have some bugs. (binder leak, surface selection, etc)
I need other's help about touch, network, audio and etc.
(I also plan to work ASAP)

**Comment by sageyun1057** [comment]
If my download, build, test is success, I will notify to you.

**Comment by sageyun1057** [comment]
I tested done.
You can check follow step.
1. down load "https://github.com/sageyun1057/anbox-modules"'s anbox10 branch
2. build binder & hwbinder and change binder, install hwbinder
3. repo init -u https://github.com/sageyun1057/platform_manifests.git -b anbox10
4. lunch anbox_x86_64-userdebug
5. (after build done) ./create-package.sh (in $TOP)
6. I can't use "--android-image" option. So I change "ANDROID_IMG" variable in container-manager.sh to my android.img

* limitation
1. Only first time rendering success. Before start anbox, you should remove data directory (/var/snap/anbox/common/data)
2. touch is not work
3. only 1 instance draw (In android side, other app running, but host side only first app draw)
4. networks is not work

**Comment by morphis** [comment]
I don't see why we need a android 10 specific branch for anbox-modules. All we need is binderfs support which is landing  with https://github.com/anbox/anbox/pull/1309 and allows Anbox to dynamically allocate the right number of binder devices. Also there is no need to copy the entire binder code just for a hwbinder device. Also binderfs support is landing in Android itself (see https://android-review.googlesource.com/c/kernel/common/+/1184061 for example) so its the way to go forward.
