### ISSUE TITLE
ls: cannot access '/dev/binder': No such file or directory

### ISSUE THREAD

**Issue by dovah32** [anbox/anbox-modules#42]
I am using ubuntu 19.10
I am unable to install anbox modules. The main problem is with last line.

`$lsmod | grep -e ashmem_linux -e binder_linux`
`binder_linux          163840  0`
`ashmem_linux           20480  0`
`$ ls -alh /dev/binder /dev/ashmem`
`ls: cannot access '/dev/binder': No such file or directory`
`crw-rw-rw- 1 root root 10, 53 Jan  1 11:35 /dev/ashmem`

**Comment by humanplayer2** [comment]
+1

**Comment by roydenyates** [comment]
> I am using ubuntu 19.10
> I am unable to install anbox modules. The main problem is with last line.
> 
> `$lsmod | grep -e ashmem_linux -e binder_linux`
> `binder_linux 163840 0`
> `ashmem_linux 20480 0`
> `$ ls -alh /dev/binder /dev/ashmem`
> `ls: cannot access '/dev/binder': No such file or directory`
> `crw-rw-rw- 1 root root 10, 53 Jan 1 11:35 /dev/ashmem`

see https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411

You can close this. not so?

**Comment by dredtaur** [comment]
Thank you for TRYING. But it's a fail and such a waste of my time.
ls: cannot access '/dev/binder': No such file or directory

**Comment by zachlai** [comment]
This way works for me:
https://superuser.com/questions/1590707/ls-cannot-access-dev-binder-no-such-file-or-directory-in-anbox
