### ISSUE TITLE
Request: please update ppa:morphis/anbox-support

### ISSUE THREAD

**Issue by AkihiroSuda** [anbox/anbox-modules#46]
@morphis 

Could you update https://launchpad.net/~morphis/+archive/ubuntu/anbox-support to include https://github.com/anbox/anbox-modules/commit/ae35b8da224b7ba163ebc1b3cf94acc2b0da260b ?

**Comment by amery** [comment]
could you extend it to cover 20.04? the ashmem_linux.ko provided by ubuntu doesn't come signed, so it doesn't load. but when built by the _dkms_ is should get automatically signed.
