### ISSUE TITLE
Tutorial to uninstall anbox-modules

### ISSUE THREAD

**Issue by yutouyes** [anbox/anbox-modules#47]
Hello everyone,
I try to manually remove anbox-modules, which is installed according to [the guide ](https://github.com/anbox/anbox-modules#install-instruction)
When runing ```sudo dkms remove anbox-binder/1 --all ``` 
An error comes
```
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/anbox-binder/1/source/dkms.conf does not exist.
```
Any advice?

**Comment by yutouyes** [comment]
I got it. Reverse the guide and it can be purged.

**Comment by ta3pks** [comment]
How did you exactly fix this I dont have any of the configs yet this broke my system I cannot run dpkg it simply fails saying 
```
Setting up linux-headers-5.8.0-7630-generic (5.8.0-7630.32~1605108806~20.10~7e52b13) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.8.0-7630-generic
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/anbox-ashmem/1/source/dkms.conf does not exist.
   ...fail!
```

**Comment by amithm7** [comment]
@NikosEfthias for the current [INSTALL.sh](https://github.com/anbox/anbox-modules/blob/98f0f3b3b1eeb5a6954ca15ec43e150b76369086/INSTALL.sh)

This should uninstall / undo those:

```sh
sudo dkms uninstall anbox-ashmem/1
sudo dkms uninstall anbox-binder/1
sudo rm -rf /usr/src/anbox-binder-1
sudo rm -rf /usr/src/anbox-ashmem-1
sudo rm /lib/udev/rules.d/99-anbox.rules
sudo rm /etc/modules-load.d/anbox.conf
sudo rm /etc/modules-load.d/waydroid.conf
```
