### ISSUE TITLE
ashmem_read cause kernel Oops

### ISSUE THREAD

**Issue by comword** [anbox/anbox-modules#7]
[ 2125.437678] BUG: unable to handle kernel paging request at 00000000408f6000
[ 2125.437688] PGD 800000080fcdc067 P4D 800000080fcdc067 PUD 78988e067 PMD 789c5e067 PTE 0
[ 2125.437696] Oops: 0002 [#1] SMP PTI
[ 2125.437699] Modules linked in: nf_conntrack_ipv6 nf_defrag_ipv6 xt_NFLOG xt_u32 xt_connmark tcp_diag inet_diag nfnetlink_log veth cpuid rfcomm xt_TCPMSS xt_tcpmss xt_comment xt_nat xt_CHECKSUM iptable_mangle ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_tcpudp tun devlink ebtable_filter ebtables ip6table_filter ip6_tables ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype xt_conntrack nf_nat nf_conntrack br_netfilter bridge overlay aufs(O) cpufreq_powersave cpufreq_conservative cpufreq_userspace msr iptable_filter pppoe pppox ppp_generic slhc cmac bnep fuse binfmt_misc nls_ascii nls_cp437 vfat fat snd_hda_codec_hdmi intel_rapl btusb btrtl btbcm btintel sb_edac bluetooth x86_pkg_temp_thermal
[ 2125.437762]  intel_powerclamp kvm_intel jitterentropy_rng 8812au(O) kvm drbg ansi_cprng ecdh_generic intel_cstate snd_virtuoso joydev cfg80211 intel_uncore snd_hda_intel snd_oxygen_lib snd_hda_codec evdev snd_mpu401_uart intel_rapl_perf usblp rfkill snd_hda_core snd_rawmidi efi_pstore snd_hwdep snd_seq_device ib_iser ast efivars snd_pcm pcspkr rdma_cm snd_timer iw_cm snd ttm ib_cm soundcore iTCO_wdt sg ib_core iTCO_vendor_support shpchp wmi configfs tpm_crb iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nvidia_drm(PO) tpm_tis tpm_tis_core drm_kms_helper tpm rng_core button drm nvidia_modeset(PO) nvidia(PO) squashfs loop ipmi_devintf ipmi_msghandler nct6775 hwmon_vid coretemp vfio_pci vfio_virqfd irqbypass vfio_iommu_type1 vfio 8021q garp mrp stp llc parport_pc ppdev lp parport binder_linux(O)
[ 2125.437831]  ashmem_linux(O) efivarfs ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 fscrypto ecb btrfs zstd_decompress zstd_compress xxhash algif_skcipher af_alg sdhci mmc_block mmc_core sd_mod dm_crypt dm_mod raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor hid_generic usbhid hid uas usb_storage raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel pcbc ehci_pci xhci_pci xhci_hcd ehci_hcd aesni_intel aes_x86_64 crypto_simd ahci cryptd glue_helper libahci mpt3sas raid_class igb i2c_algo_bit libata scsi_transport_sas usbcore dca i2c_i801 lpc_ich usb_common scsi_mod
[ 2125.437895] CPU: 8 PID: 24493 Comm: AsyncTask #4 Tainted: P           O      4.17.0-1-amd64 #1 Debian 4.17.8-1
[ 2125.437897] Hardware name: 
[ 2125.437906] RIP: 0010:memcpy_erms+0x6/0x10
[ 2125.437908] RSP: 0018:ffffa8334fb7fca8 EFLAGS: 00010206
[ 2125.437911] RAX: 00000000408f500c RBX: 0000000000001000 RCX: 000000000000000c
[ 2125.437914] RDX: 0000000000001000 RSI: ffff955039ecfff4 RDI: 00000000408f6000
[ 2125.437916] RBP: 0000000000001000 R08: fffff7d85ce7b3dc R09: fffff7d85ce7b3c0
[ 2125.437919] R10: 0000000000000000 R11: ffff955039ecf000 R12: ffffa8334fb7fe18
[ 2125.437921] R13: 0000000000001000 R14: ffff955039ed0000 R15: ffffa8334fb7fde0
[ 2125.437924] FS:  00007f9b191ff4e8(0000) GS:ffff95515f800000(0000) knlGS:00007f9b192d3000
[ 2125.437927] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 2125.437929] CR2: 00000000408f6000 CR3: 000000078a0b6005 CR4: 00000000001606e0
[ 2125.437931] Call Trace:
[ 2125.437940]  _copy_to_iter+0x286/0x3d0
[ 2125.437945]  copy_page_to_iter+0x1b4/0x2f0
[ 2125.437952]  shmem_file_read_iter+0xea/0x320
[ 2125.437959]  new_sync_read+0xe9/0x140
[ 2125.437964]  vfs_read+0x89/0x130
[ 2125.437968]  kernel_read+0x2c/0x40
[ 2125.437975]  ashmem_read+0x5c/0xa0 [ashmem_linux]
[ 2125.437979]  vfs_read+0x89/0x130
[ 2125.437983]  ksys_read+0x52/0xc0
[ 2125.437992]  do_syscall_64+0x55/0x110
[ 2125.437998]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 2125.438002] RIP: 0033:0x7f9b35dc02e7
[ 2125.438004] RSP: 002b:00007f9b191fe738 EFLAGS: 00000202 ORIG_RAX: 0000000000000000
[ 2125.438007] RAX: ffffffffffffffda RBX: 00007f9b2d41c680 RCX: 00007f9b35dc02e7
[ 2125.438009] RDX: 000000000000e758 RSI: 00000000408f500c RDI: 0000000000000031
[ 2125.438012] RBP: 0000000000000031 R08: 0000000000000000 R09: 000000000000e758
[ 2125.438014] R10: 000000007079e000 R11: 0000000000000202 R12: 00000000408f500c
[ 2125.438016] R13: 0000000000000000 R14: 00007f9b191fe770 R15: 00007f9b2d41c680
[ 2125.438019] Code: 90 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 
[ 2125.438065] RIP: memcpy_erms+0x6/0x10 RSP: ffffa8334fb7fca8
[ 2125.438067] CR2: 00000000408f6000
[ 2125.438070] ---[ end trace 0d2e777423428bd4 ]---

**Comment by morphis** [comment]
The report doesn't give much information about which kernel version was used etc. @comword Can please give us more details. Thanks.

**Comment by comword** [comment]
After use the code from the mainline kernel source code the Oops went away.
