### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aliraza5490** [anbox/anbox-modules#70]
### Console:
sudo: dkms: command not found
sudo: dkms: command not found
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted
binder_linux          180224  0
ls: cannot access '/dev/binder': No such file or directory
ls: cannot access '/dev/ashmem': No such file or directory

**Comment by vincent456** [comment]
install the dkms package

**Comment by aliraza5490** [comment]
@vincent456 thanks
