### ISSUE TITLE
Cannot Build on linux-zen 5.10

### ISSUE THREAD

**Issue by mokurin000** [anbox/anbox-modules#72]

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….

**Comment by mokurin000** [comment]
linux-zen removed blender support in 5.10.4.
